### ISSUE TITLE
Do not output any message `quite` global flag

### ISSUE THREAD

**Issue by octoper** [lanvard/foundation#20]
I have been trying to implement that but don't got any luck, so I wanted to create that issue.

It would be nice to have a global `--quite` flag, so when this flag is presented, every output message will go from
`os.Stdout` to `ioutil.Discard` and `os.Stderr` to `ioutil.Discard` and nothing will be displayed on the terminal.

**Comment by reindert-vetter** [comment]
That is difficult. I don't know if we can overwrite `os.Stdout` like that. We can also make it so that no confetti logs are written (to stdout).

But where do you want to use this for? Is this something you need?

**Comment by octoper** [comment]
I have tried it and we can just set the drivers to `ioutil.Discard` in the console kernel  but I can't figure out how to make a proper Global flag.

It's nice when you run a command with lot of output and you want to keep your terminal clean.

**Comment by reindert-vetter** [comment]
1. Make a test where you expect the new flag. (you can use [this test](https://github.com/confetti-framework/foundation/blob/main/test/console/command_index_test.go#L39))
2. You have to add the flag to show in the index [in help.go](https://github.com/confetti-framework/foundation/blob/main/console/service/help.go#L22-L24)
3. Make a test in which you pass that argument. (like [this](https://github.com/confetti-framework/foundation/blob/main/test/console/options_test.go#L204))
3. Then you can (where you want to silence the output) walk over the parameters and check whether it is present. Normally you could just use `os.Args`, but it's not easy to test. That is why you can also get the settings from app with `app.Make("config.App.OsArgs")`. [Where](https://github.com/confetti-framework/foundation/blob/main/console/service/flags.go#L20) we covert the parameters in a slice with strings.

Does this also have any effect on baker (`go run main.go baker`)?  Or is this really only affects Confetti log drivers? Suppose you use the slack driver, will they be sent?

**Comment by octoper** [comment]
I will try it. Thank you!
I'm not 100% sure about Baker but I don't think it will affect it I will just change the `c.Writer`

**Comment by reindert-vetter** [comment]
Okay, then (I think) it doesn't affect baker.

**Comment by reindert-vetter** [comment]
Okay, then (I think) it doesn't affect Baker.
